import { ActivityEvent } from '@/types';

export const mockRecentActivity: ActivityEvent[] = [
  {
    id: 'act_001',
    time: '10:31 AM',
    recipient: 'contact@example.com',
    campaign: 'First Client Outreach',
    event: 'Email sent',
    status: 'SUCCESS',
  },
  {
    id: 'act_002',
    time: '10:30 AM',
    recipient: 'person@example.com',
    campaign: 'First Client Outreach',
    event: 'Delivered',
    status: 'SUCCESS',
  },
  {
    id: 'act_003',
    time: '10:29 AM',
    recipient: 'another@example.com',
    campaign: 'First Client Outreach',
    event: 'Hard bounce',
    status: 'FAILED',
  },
  {
    id: 'act_004',
    time: '10:28 AM',
    recipient: 'user@example.com',
    campaign: 'Product Launch Test',
    event: 'Blocked',
    status: 'BLOCKED',
  },
  {
    id: 'act_005',
    time: '10:26 AM',
    recipient: 'operations@example.com',
    campaign: 'First Client Outreach',
    event: 'Delivered',
    status: 'SUCCESS',
  },
  {
    id: 'act_006',
    time: '10:24 AM',
    recipient: 'devlead@example.com',
    campaign: 'First Client Outreach',
    event: 'Email sent',
    status: 'SUCCESS',
  },
  {
    id: 'act_007',
    time: '10:20 AM',
    recipient: 'inbox-full@example.org',
    campaign: 'Product Launch Test',
    event: 'Soft bounce (mailbox full)',
    status: 'WARNING',
  },
  {
    id: 'act_008',
    time: '10:17 AM',
    recipient: 'founder@example.io',
    campaign: 'First Client Outreach',
    event: 'Delivered',
    status: 'SUCCESS',
  },
  {
    id: 'act_009',
    time: '10:14 AM',
    recipient: 'marketing@example.co',
    campaign: 'First Client Outreach',
    event: 'Delivered',
    status: 'SUCCESS',
  },
  {
    id: 'act_010',
    time: '10:10 AM',
    recipient: 'optout@example.net',
    campaign: 'Product Launch Test',
    event: 'Suppression match (unsubscribed)',
    status: 'BLOCKED',
  },
];
