import { Campaign, CampaignSummary } from '@/types';

export const mockCampaignSummaries: CampaignSummary[] = [
  {
    id: 'cmp_first_client_01',
    name: 'First Client Outreach',
    key: 'first_client_outreach',
    description: 'High-touch personalized sequence for prospective design partners.',
    status: 'RUNNING',
    maxRecipients: 500,
    sent: 87,
    remaining: 413,
    dailyLimit: 100,
    hourlyLimit: 20,
    perMinuteLimit: 1,
    progressPercentage: 17.4,
    lastActivity: '2 minutes ago',
  },
  {
    id: 'cmp_product_launch_02',
    name: 'Product Launch Test',
    key: 'product_launch_test',
    description: 'Initial beta invites to test deliverability envelope & feedback rate.',
    status: 'PAUSED',
    maxRecipients: 250,
    sent: 42,
    remaining: 208,
    dailyLimit: 50,
    hourlyLimit: 10,
    perMinuteLimit: 1,
    progressPercentage: 16.8,
    lastActivity: '1 hour ago',
  },
  {
    id: 'cmp_followup_03',
    name: 'Follow-up Campaign',
    key: 'follow_up_sequence',
    description: 'Automated 3-day follow-up for recipients who did not open email 1.',
    status: 'SCHEDULED',
    maxRecipients: 100,
    sent: 0,
    remaining: 100,
    dailyLimit: 25,
    hourlyLimit: 5,
    perMinuteLimit: 1,
    progressPercentage: 0,
    lastActivity: 'Tomorrow at 09:00 AM',
  },
  {
    id: 'cmp_founder_pilot_04',
    name: 'Founder Pilot Cohort',
    key: 'founder_pilot_cohort',
    description: 'Closed pilot group outreach verified across Brevo deliverability sandbox.',
    status: 'COMPLETED',
    maxRecipients: 300,
    sent: 300,
    remaining: 0,
    dailyLimit: 60,
    hourlyLimit: 15,
    perMinuteLimit: 1,
    progressPercentage: 100,
    lastActivity: '3 days ago',
  },
  {
    id: 'cmp_retarget_05',
    name: 'High-Value ICP Retargeting',
    key: 'high_value_icp',
    description: 'Account-based sequence with strict per-minute throttle.',
    status: 'FAILED',
    maxRecipients: 150,
    sent: 12,
    remaining: 138,
    dailyLimit: 30,
    hourlyLimit: 6,
    perMinuteLimit: 1,
    progressPercentage: 8.0,
    lastActivity: 'Yesterday (SMTP timeout)',
  },
];

// Mapped full Campaign object for views that inspect deeper fields
export const mockCampaigns: Campaign[] = mockCampaignSummaries.map((c) => ({
  ...c,
  max_recipients: c.maxRecipients,
  sent_count: c.sent,
  remaining_count: c.remaining,
  queued_count: Math.round(c.remaining * 0.3),
  failed_count: c.status === 'FAILED' ? 12 : c.sent > 0 ? 1 : 0,
  blocked_count: Math.round(c.sent * 0.05),
  emails_per_day: c.dailyLimit,
  emails_per_hour: c.hourlyLimit || 20,
  emails_per_minute: c.perMinuteLimit || 1,
  batch_size: 5,
  created_at: '2026-09-28T09:00:00Z',
  started_at: '2026-09-29T10:15:00Z',
  today_sent: c.status === 'RUNNING' ? 87 : 0,
  hour_sent: c.status === 'RUNNING' ? 14 : 0,
  minute_sent: c.status === 'RUNNING' ? 1 : 0,
}));
